/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefetrj.mg.bsi.sisbiblio.view;

import static br.cefetrj.mg.bsi.sisbiblio.config.Settings.*;
import static br.cefetrj.mg.bsi.utils.Utils.confirm;
import javax.swing.JButton;
import javax.swing.JTextField;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;


/**
 *
 * @author cristian
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    
    public Dashboard() {
        initComponents();
        restoreView();
        
        
    }
    /*
    *@param boolean 
    */
    private void showFormObra(){
        pnlObra.setVisible(!pnlObra.isVisible());
        pnlTable.setVisible(!pnlTable.isVisible());
        pnlButton.setVisible(!pnlButton.isVisible());
    }
    private void showFormAutor(){
        
    }
    private void autocomplete(){
        //AutoCompleteDecorator.
    }
    private void restoreView(){
        pnlForm.setVisible(true);
        pnlTable.setVisible(true);
        pnlObra.setVisible(false);
        pnlButton.setVisible(false);
    }

    public JButton getBtnCadastrarAtualizar() {
        return btnCadastrarAtualizar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JTextField getTxtISBN() {
        return txtISBN;
    }

    public JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        pnlMenuAutor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenuObra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlHead = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlForm = new javax.swing.JPanel();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnlObra = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAutor = new org.jdesktop.swingx.JXTable();
        txtPesquisarAutor = new org.jdesktop.swingx.JXSearchField();
        pnlButton = new javax.swing.JPanel();
        btnCadastrarAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisBiblio-Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(0, 102, 255));
        pnlMenu.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuAutor.setBackground(new java.awt.Color(51, 153, 255));
        pnlMenuAutor.setToolTipText("");
        pnlMenuAutor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefetrj/mg/bsi/sisbiblio/icon/twotone_person_add_black_24dp.png"))); // NOI18N
        jLabel2.setText("Autor");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        pnlMenuAutor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        pnlMenu.add(pnlMenuAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, 60));

        pnlMenuObra.setBackground(new java.awt.Color(51, 153, 255));
        pnlMenuObra.setToolTipText("");
        pnlMenuObra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefetrj/mg/bsi/sisbiblio/icon/twotone_book_black_24dp.png"))); // NOI18N
        jLabel1.setText("Obras");
        pnlMenuObra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        pnlMenu.add(pnlMenuObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 60));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        pnlHead.setBackground(new java.awt.Color(204, 204, 204));
        pnlHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefetrj/mg/bsi/sisbiblio/icon/twotone_close_black_18dp.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        pnlHead.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, 50));

        getContentPane().add(pnlHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 50));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTable.setBackground(new java.awt.Color(255, 255, 255));
        pnlTable.setForeground(new java.awt.Color(204, 204, 204));
        pnlTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setForeground(new java.awt.Color(204, 204, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Editar", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(20);
            table.getColumnModel().getColumn(0).setPreferredWidth(20);
            table.getColumnModel().getColumn(0).setMaxWidth(20);
            table.getColumnModel().getColumn(1).setMinWidth(100);
            table.getColumnModel().getColumn(1).setPreferredWidth(100);
            table.getColumnModel().getColumn(1).setMaxWidth(100);
            table.getColumnModel().getColumn(2).setMinWidth(100);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
            table.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        pnlTable.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 580, 320));

        txtPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPesquisa.setForeground(new java.awt.Color(51, 51, 51));
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        pnlTable.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 530, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefetrj/mg/bsi/sisbiblio/icon/twotone_search_black_24dp.png"))); // NOI18N
        pnlTable.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 60, 40));

        pnlForm.add(pnlTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pnlObra.setBackground(new java.awt.Color(255, 255, 255));
        pnlObra.setForeground(new java.awt.Color(204, 204, 204));
        pnlObra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Título");
        pnlObra.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 30));

        txtTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        pnlObra.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 560, 40));

        txtISBN.setBackground(new java.awt.Color(255, 255, 255));
        txtISBN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtISBN.setForeground(new java.awt.Color(51, 51, 51));
        pnlObra.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 560, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ISBN");
        pnlObra.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 30));

        tableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableAutor);

        pnlObra.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 560, 110));

        txtPesquisarAutor.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisarAutor.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisarAutor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPesquisarAutor.setPrompt(" Digite o nome ou email de um autor...");
        pnlObra.add(txtPesquisarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 560, 40));

        pnlForm.add(pnlObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pnlButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlButton.setForeground(new java.awt.Color(204, 204, 204));
        pnlButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrarAtualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadastrarAtualizar.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastrarAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefetrj/mg/bsi/sisbiblio/icon/baseline_add_black_18dp.png"))); // NOI18N
        btnCadastrarAtualizar.setText("Cadastrar");
        pnlButton.add(btnCadastrarAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 50));

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(51, 51, 51));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefetrj/mg/bsi/sisbiblio/icon/baseline_delete_black_18dp.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlButton.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 250, 50));

        pnlForm.add(pnlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 580, 100));

        pnlBody.add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        getContentPane().add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 600, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if(confirm("Deseja sair?", TITLE) == 0){
            System.exit(0);
        }
            
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        showFormObra();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(confirm("Deseja realmente excluir?", TITLE) == 0){
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuAutor;
    private javax.swing.JPanel pnlMenuObra;
    private javax.swing.JPanel pnlObra;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable table;
    private org.jdesktop.swingx.JXTable tableAutor;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtPesquisa;
    private org.jdesktop.swingx.JXSearchField txtPesquisarAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
